# Exported from:        http://gram-digitalai:5516/
# Release version:      23.1.6
# Date created:         Wed Aug 23 16:40:23 IST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
