# Exported from:        http://gram-digitalai:5516/
# Release version:      23.1.6
# Date created:         Wed Aug 23 16:40:23 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: test_folder
spec:
- template: Jenkins_Job_1
  scheduledStartDate: 2023-04-21T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: j1
      type: jenkins.Build
      jenkinsServer: global_sam_jenkins
      jobName: sam_195048
  variables:
  - type: xlrelease.StringVariable
    key: sam_variable
    requiresValue: false
    showOnReleaseStart: false
    value: test_value
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Jenkins_Job_1_scriptUserPassword"
  riskProfile: Default risk profile
